# Generated by Django 5.2.17 on 2026-09-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_confirm_approved_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
