# Generated by Django 5.2.17 on 2026-09-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_school_is_active_tailoringcenter_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='description',
            field=models.CharField(blank=True, help_text='Who this kit is for, in a sentence. Shown to schools choosing one.', max_length=300),
        ),
    ]
