# Generated by Django 5.2.17 on 2026-09-17 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_sku_readable_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='colour_hex',
            field=models.CharField(blank=True, help_text='The swatch for this colour, as "#RRGGBB". Optional.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', message='A colour must look like "#1e3a8a".')]),
        ),
        migrations.AddField(
            model_name='school',
            name='student_count',
            field=models.PositiveIntegerField(blank=True, help_text='Pupils enrolled. Left blank until the school reports it.', null=True),
        ),
    ]
