# Generated by Django 5.2.17 on 2026-09-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_school_students_and_garment_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='student_count',
            field=models.PositiveIntegerField(blank=True, help_text='Students enrolled. Left blank until the school reports it.', null=True),
        ),
    ]
