# Generated by Django 5.2.17 on 2026-09-14 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_school_is_active_tailoringcenter_is_active_and_more'),
        ('orders', '0008_schoolorder_priority_shipment_carrier_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolorder',
            name='fulfilled_by_warehouse',
            field=models.ForeignKey(blank=True, help_text="Set when the order was transferred to a warehouse holding stock. Empty means the school's own warehouse fills it.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_accepted', to='catalog.warehouse'),
        ),
        migrations.AddField(
            model_name='schoolorder',
            name='transfer_reason',
            field=models.CharField(blank=True, help_text="Why it moved. Recorded because a transfer is a person's judgement, not a rule the system applied.", max_length=200),
        ),
        migrations.AddField(
            model_name='schoolorder',
            name='transferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolorder',
            name='transferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
